import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex font-semibold text-lg text-gray-800 justify-center">
            Welcome to the Dashboard 🚀
      </main>

    </div>
  )
}
